try:
    print(x)
except:
    print("an error occurred")
finally:
    print("Success")